include:
  - project: 'sysadm-docker/ubuntu-sshclient'
    ref:     'master'
    file:    'gitlab-ci-template.yml'

image: circleci/android:api-29

stages:
  - generate_keystore
  - build
  - lint
  - test
  - publish
  - build_doc
  - deploy
  - linking

generate_keystore:
  stage: generate_keystore
  except:
    - branches
  script:
    - echo $STORE_FILE | base64 -di > xsolla.keystore
    - echo "keystorePath=../xsolla.keystore" > signing.properties
    - echo "keystorePassword=$STORE_PASSWORD" >> signing.properties
    - echo "keyAlias=$KEY_ALIAS" >> signing.properties
    - echo "keyPassword=$KEY_PASSWORD" >> signing.properties
  artifacts:
    paths:
      - xsolla.keystore
      - signing.properties
    expire_in: 30 mins

build:
  stage: build
  except:
    - branches
  script:
    - ./gradlew assembleRelease
  artifacts:
    expire_in: 2 hours
    paths:
      - app/build/outputs/
      - app-inventory/build/outputs/
      - app-customauth/build/outputs/
  cache:
    key: ${CI_PROJECT_ID}
    paths:
      - .gradle/*

lint:
  stage: lint
  except:
    - branches
  script:
    - ./gradlew lint
  artifacts:
    expire_in: 24 hours
    paths:
      - app/build/reports/
      - app-inventory/build/reports/
      - app-customauth/build/reports/
      - xsolla-inventory-sdk/build/reports/
      - xsolla-login-sdk/build/reports/
      - xsolla-login-sdk-facebook/build/reports/
      - xsolla-login-sdk-google/build/reports/
      - xsolla-login-sdk-qq/build/reports/
      - xsolla-login-sdk-wechat/build/reports/
      - xsolla-payments-sdk/build/reports/
      - xsolla-store-sdk/build/reports/
  cache:
    key: ${CI_PROJECT_ID}
    paths:
      - .gradle/*

test:
  stage: test
  except:
    - branches
  script:
    - ./gradlew :xsolla-login-sdk:setupTestVariables && ./gradlew :xsolla-login-sdk:test
    - ./gradlew :xsolla-store-sdk:setupTestVariables && ./gradlew :xsolla-store-sdk:test
    - ./gradlew :xsolla-inventory-sdk:setupTestVariables && ./gradlew :xsolla-inventory-sdk:test
  artifacts:
    expire_in: 24 hours
    paths:
      - xsolla-login-sdk/build/reports/
      - xsolla-store-sdk/build/reports/
      - xsolla-inventory-sdk/build/reports/
  cache:
    key: ${CI_PROJECT_ID}
    paths:
      - .gradle/*

generateReleaseApp:
  stage: publish
  except:
    - branches
  before_script:
    - mkdir -p artifacts
    - touch ./artifacts/info.txt
    - echo "Build date          $(date)"                >> ./artifacts/info.txt
    - echo "Git tag             ${CI_COMMIT_REF_NAME}"  >> ./artifacts/info.txt
    - echo "Git commit          ${CI_COMMIT_SHA}"       >> ./artifacts/info.txt
    - echo "Gitlab pipeline     ${CI_PIPELINE_ID}"      >> ./artifacts/info.txt
  script:
    - mv app/build/outputs/apk/release/app-release.apk ./artifacts/SampleApp-Default.apk
    - mv app-inventory/build/outputs/apk/release/app-inventory-release.apk ./artifacts/SampleApp-Inventory.apk
    - mv app-customauth/build/outputs/apk/release/app-customauth-release.apk ./artifacts/SampleApp-Customauth.apk
  artifacts:
    expire_in: 24 hours
    paths:
      - artifacts

publishLogin:
  stage: publish
  when: manual
  only:
    - /^v.*/
  except:
    - branches
  script:
    - ./gradlew :xsolla-login-sdk:bintrayUpload
    - ./gradlew :xsolla-login-sdk-facebook:bintrayUpload
    - ./gradlew :xsolla-login-sdk-google:bintrayUpload
    - ./gradlew :xsolla-login-sdk-wechat:bintrayUpload
  cache:
    key: ${CI_PROJECT_ID}
    paths:
      - .gradle/*

publishStore:
  stage: publish
  when: manual
  only:
    - /^v.*/
  except:
    - branches
  script:
    - ./gradlew :xsolla-store-sdk:bintrayUpload
  cache:
    key: ${CI_PROJECT_ID}
    paths:
      - .gradle/*

publishInventory:
  stage: publish
  when: manual
  only:
    - /^v.*/
  except:
    - branches
  script:
    - ./gradlew :xsolla-inventory-sdk:bintrayUpload
  cache:
    key: ${CI_PROJECT_ID}
    paths:
      - .gradle/*

publishPayments:
  stage: publish
  when: manual
  only:
    - /^v.*/
  except:
    - branches
  script:
    - ./gradlew :xsolla-payments-sdk:bintrayUpload
  cache:
    key: ${CI_PROJECT_ID}
    paths:
      - .gradle/*

build doc:
  stage: build_doc
  only:
    - /^v.*/
  script:
    - ./gradlew dokkaHtmlMultiModule
    - cd build/dokka/htmlMultiModule/ && mv -- '-modules.html' index.html && zip -r ../../../build.zip *
  artifacts:
    expire_in: 24 hours
    paths:
      - build.zip

deploy doc:
  stage: deploy
  extends:      .deploy doc
  only:
    - /^v.*/
  dependencies:
    - build doc
  environment:
    name: doc/$CI_COMMIT_REF_SLUG
    url: https://$CI_PROJECT_NAME-$CI_COMMIT_REF_NAME.doc.srv.local/$URL_SLUG
    on_stop: stop doc
  when: manual

current doc:
  extends:      .current doc
  only:
    - /^v.*/
  dependencies:
    - deploy doc
  environment:
    name: doc/current
    url: https://developers.xsolla.com/sdk-code-references/android-store

stop doc:
  extends:      .stop doc
  environment:
    name: doc/$CI_COMMIT_REF_SLUG
    action: stop
  only:
    - /^v.*/
  dependencies: []